services:
  api:
    build: .
    container_name: social_media_api
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
